#!/bin/bash
cd /var/www/phplaravel
amazon-linux-extras install php7.3=7.3.13
sudo yum -y update
sudo yum -y install php-mbstring-7.3.13-1.amzn2 php-pecl-mcrypt-1.0.1-3.amzn2.0.2 php-devel-7.3.13-1.amzn2 php-xml-7.3.13-1.amzn2
sudo curl -s https://getcomposer.org/installer | php
sudo php composer.phar install
sudo php composer.phar update
sudo mv composer.phar /usr/local/bin/composer
sudo cp .env.example .env